<?php

// Параметры плагина по умолчанию 
define('UNIMAPS_PLUGIN_STYLE',      'placemarks');


function unimaps_views_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'unimaps_views'),
  );
}

// Определение списка параметров метки для views
function unimaps_views_get_objects($result, $handlers) {

  $pm = array();

  if ($result) {

    foreach($result as $obj) {

      // nid ноды
      $nid = $obj->nid;
      // тип материала
      $bundle = $obj->_field_data['nid']['entity']->type;
      // ноазвание поля unimaps в этом материале
      $field_name = unimaps_get_fields($bundle);
      // содержимое поля
      $field = $obj->_field_data['nid']['entity']->$field_name;

      foreach($field[LANGUAGE_NONE] as $delta => $name) {

        // извлечение информации о линии
        if ($bundle == 'ym_polyline' && $delta == 0) {
          if (isset($name['data'])) {
            $data = unserialize($name['data']);
            if (isset($data['polyline'])) {
              $pm['lines'][$nid] = $data['polyline'];
              if (isset($data['polyline']['points'])) $pm['lines'][$nid]['points'] = unimaps_coords_decode($data['polyline']['points']);
              if (!empty($name['name'])) $pm['lines'][$nid]['ym_pl_name'] = $name['name'];
              if (!empty($name['descr']) && user_access('view balloon content')) $pm['lines'][$nid]['ym_pl_descr'] = $name['descr'];
            }
          }
        }

        // извлечение информации о полиноме
        elseif ($bundle == 'ym_polygon' && $delta == 0) {
          if (isset($name['data'])) {
            $data = unserialize($name['data']);
            if (isset($data['polygon'])) {
              $pm['polygones'][$nid] = $data['polygon'];
              if (isset($data['polygon']['points'])) $pm['polygones'][$nid]['points'] = unimaps_coords_decode($data['polygon']['points']);
              if (!empty($name['name'])) $pm['polygones'][$nid]['ym_pg_name'] = $name['name'];
              if (!empty($name['descr']) && user_access('view balloon content')) $pm['polygones'][$nid]['ym_pg_descr'] = $name['descr'];
            }
          }
        }

        // извлечение информации о метках
        else if ($name['lat'] != UNIMAPS_LATITUDE && $name['lng'] != UNIMAPS_LONGITUDE) {
          $pid = $nid . '-' . $delta;
          $pm['placemarks'][$pid]['lat'] = $name['lat'];
          $pm['placemarks'][$pid]['lng'] = $name['lng'];
          if (!empty($name['name'])) $pm['placemarks'][$pid]['title'] = $name['name'];
          if (!empty($name['descr'])) $pm['placemarks'][$pid]['descr'] = $name['descr'];
          if (!empty($name['yandex_icon']) && user_access('view balloon content')) $pm['placemarks'][$pid]['yandex_icon'] = $name['yandex_icon'];
        }

      }

    }
  }

  return $pm;
}